# Generated by Django 6.0 on 2026-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
