# Generated by Django 6.0 on 2026-01-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_studentprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_resume_fake',
            field=models.BooleanField(default=False, help_text='True if resume is detected as copied or fake'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_similarity_score',
            field=models.FloatField(default=0.0, help_text='Similarity percentage with other resumes'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_warning',
            field=models.CharField(blank=True, help_text='Warning message shown to student', max_length=255),
        ),
    ]
