# Generated by Django 6.0 on 2026-01-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_studentprofile_is_resume_fake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of resume for duplicate detection', max_length=64, null=True),
        ),
    ]
