# Generated by Django 6.0 on 2026-01-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_studentprofile_resume_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_email',
            field=models.EmailField(blank=True, help_text='Email used for placement notifications', max_length=254, null=True),
        ),
    ]
