# Generated by Django 6.0 on 2026-01-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_studentprofile_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by employer when rejecting application', null=True),
        ),
    ]
