# Generated by Django 6.0.1 on 2026-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_remove_job_company_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
