# Generated by Django 6.0.1 on 2026-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_employerprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
