# Generated by Django 6.0.1 on 2026-02-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_job_job_type_job_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
